image: Visual Studio 2022
version: 1.0.{build}
platform: x64
configuration: Release
environment:
  VCPKG_DEFAULT_TRIPLET: x64-windows-static-md
  VCPKG_HASH: cc97b4536ae749ec0e4f643488b600b217540fb3
install:
  # get all submodules
  - git submodule update --init --recursive
  # checkout specific vcpkg commit
  #- pushd C:\Tools\vcpkg && git log -1 && popd
  #- pushd C:\Tools\vcpkg && git fetch && git checkout %VCPKG_HASH% && git log -1 && popd
  #- pushd C:\Tools\vcpkg && .\bootstrap-vcpkg.bat -disableMetrics && popd
  # force release build type (disables debug builds)
  - echo.set(VCPKG_BUILD_TYPE release)>> C:\Tools\vcpkg\triplets\community\x64-windows-static-md.cmake
  # set up visual studio prompt
  - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
  # install dependencies (note: polyhook2 needs asmjit and asmtk explicitly listed)
  - vcpkg integrate install
  - vcpkg install spdlog asmjit asmtk polyhook2[core,pe,virtuals] ffmpeg[core,avformat,avcodec,swresample,swscale,nvcodec,mp3lame,opencl,openjpeg,opus,snappy,soxr,speex,theora,vorbis,vpx,webp,zlib]
  - ps: |
      if (Test-Path "sdk\sdk.zip" -PathType leaf)
      {
        cd sdk
        Invoke-WebRequest -Uri "http://www.dev-c.com/files/ScriptHookV_SDK_1.0.617.1a.zip" -OutFile "sdk.zip" -Headers @{ "Referer" = "http://www.dev-c.com/gtav/scripthookv/" }
        7z x sdk.zip
        cd ..
      }
build: off
build_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static-md ..
  - ninja
after_build:
  - ps: Copy-Item -Path "..\plugin\*.ini" -Destination .
  - ps: Copy-Item -Path "..\test\*.ini" -Destination .
  - dir /b *.asi *.exe *.ini
  - 7z a ..\SimpleVideoExport-git-%APPVEYOR_BUILD_VERSION%.7z *.asi *.exe *.ini
test: off
artifacts:
  - path: SimpleVideoExport-git-$(APPVEYOR_BUILD_VERSION).7z
cache:
  - c:\tools\vcpkg\installed\ -> appveyor.yml
  - sdk\sdk.zip -> appveyor.yml
