image: Visual Studio 2019
version: 1.0.{build}
platform: x64
configuration: Release
install:
  - git submodule update --init --recursive
  - set VCPKG_DEFAULT_TRIPLET=x64-windows-static-md
  - vcpkg integrate install
  - vcpkg install polyhook2
  - vcpkg install ffmpeg[vpx]
build-script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -G Ninja ..
  - ninja
after_build:
  - pushd build\x64-Release\
  - ps: Copy-Item -Path "..\..\plugin\*.ini" -Destination .
  - ps: Copy-Item -Path "..\..\test\*.ini" -Destination .
  - dir /s /b *.asi *.exe *.ini
  - 7z a -r ..\..\SimpleVideoExport-git-%APPVEYOR_BUILD_VERSION%.7z *.asi *.exe *.ini
test: off
artifacts:
  - path: SimpleVideoExport-git-$(APPVEYOR_BUILD_VERSION).7z
cache: c:\tools\vcpkg\installed\
