image: Visual Studio 2019
version: 1.0.{build}
platform: x64
configuration: Release
environment:
  VCPKG_DEFAULT_TRIPLET: x64-windows-static-md
  VCPKG_HASH: 18ab4b72a26284f0df28295ce7bf9b21c96f20f4
install:
  # get all submodules
  - git submodule update --init --recursive
  # checkout specific vcpkg commit
  - pushd C:\Tools\vcpkg && git log -1 && popd
  - pushd C:\Tools\vcpkg && git fetch && git checkout %VCPKG_HASH% && git log -1 && popd
  - pushd C:\Tools\vcpkg && .\bootstrap-vcpkg.bat -disableMetrics && popd
  # fix msys issue on appveyor
  - ps: Copy-Item -Path "vcpkg_acquire_msys.cmake" -Destination "c:\tools\vcpkg\scripts\cmake\"
  # force release build type (disables debug builds)
  - echo.set(VCPKG_BUILD_TYPE release)>> C:\Tools\vcpkg\triplets\community\x64-windows-static-md.cmake
  # set up visual studio prompt
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  # install dependencies
  - vcpkg integrate install
  - vcpkg install spdlog
  - vcpkg install polyhook2[core,pe,virtuals]
  - vcpkg install ffmpeg[core,avformat,avcodec,avfilter,swresample,swscale,nvcodec,opus,snappy,soxr,vpx,wavpack]
build_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static-md ..
  - ninja
after_build:
  - ps: Copy-Item -Path "..\plugin\*.ini" -Destination .
  - ps: Copy-Item -Path "..\test\*.ini" -Destination .
  - dir /b *.asi *.exe *.ini
  - 7z a ..\SimpleVideoExport-git-%APPVEYOR_BUILD_VERSION%.7z *.asi *.exe *.ini
test: off
artifacts:
  - path: SimpleVideoExport-git-$(APPVEYOR_BUILD_VERSION).7z
cache: c:\tools\vcpkg\installed\ -> appveyor.yml
