image: Visual Studio 2019
version: 1.0.{build}
platform: x64
configuration: Release
environment:
  VCPKG_DEFAULT_TRIPLET: x64-windows-static-md
install:
  # checkout specific vcpkg version, latest master has zlib install bug
  - cd c:\tools\vcpkg\
  - git fetch
  - git checkout 077c0746be3773fdd443af52cbe5c3cc26379a15
  - .\bootstrap-vcpkg.bat -disableMetrics
  - cd %APPVEYOR_BUILD_FOLDER%
  # get all submodules
  - git submodule update --init --recursive
  # fix msys issue on appveyor
  - ps: Copy-Item -Path "vcpkg_acquire_msys.cmake" -Destination "c:\tools\vcpkg\scripts\cmake\"
  # force release build type (disables debug builds)
  - echo.set(VCPKG_BUILD_TYPE release)>> C:\Tools\vcpkg\triplets\community\x64-windows-static-md.cmake
  # set up visual studio prompt
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  # install dependencies
  - vcpkg integrate install
  - vcpkg install spdlog
  - vcpkg install polyhook2[core,pe,virtuals]
  - vcpkg install ffmpeg[vpx]
build_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static-md ..
  - ninja
  - dir /s /b
after_build:
  - pushd build\
  - ps: Copy-Item -Path "..\plugin\*.ini" -Destination .
  - ps: Copy-Item -Path "..\test\*.ini" -Destination .
  - dir /s /b *.asi *.exe *.ini
  - 7z a -r ..\SimpleVideoExport-git-%APPVEYOR_BUILD_VERSION%.7z *.asi *.exe *.ini
test: off
artifacts:
  - path: SimpleVideoExport-git-$(APPVEYOR_BUILD_VERSION).7z
cache: c:\tools\vcpkg\installed\
