image: Visual Studio 2019 Preview
version: 1.0.{build}
install:
  - git submodule update --init --recursive
  - nuget restore
platform: x64
configuration: Release
build:
  project: gta5-simple-video-export.sln
after_build:
  - pushd x64\Release
  - ps: Copy-Item -Path "..\..\plugin\*.ini" -Destination .
  - ps: Copy-Item -Path "..\..\test\*.ini" -Destination .
  - dir /s /b *.asi *.exe *.ini
  - 7z a -r ..\..\SimpleVideoExport-git-%APPVEYOR_BUILD_VERSION%.7z *.asi *.exe *.ini
test: off
artifacts:
  - path: SimpleVideoExport-git-$(APPVEYOR_BUILD_VERSION).7z
